local Animations = {}

Animations.emotes = {
    ["Air Synth"] = { "anim@mp_player_intcelebrationfemale@air_synth", "air_synth", "Air Synth" },
    ["Binoculars"] = { "Scenario", "WORLD_HUMAN_BINOCULARS", "Binoculars" },
    ["Blow Kiss 1"] = { "anim@mp_player_intcelebrationfemale@blow_kiss", "blow_kiss", "Blow Kiss 1" },
    ["Blow Kiss 2"] = { "anim@mp_player_intselfieblow_kiss", "exit", "Blow Kiss 2", AnimationOptions = { EmoteMoving = true, EmoteDuration = 2000 } },
    ["Bird"] = { "random@peyote@bird", "wakeup", "Bird" },
    ["Celebrate"] = { "rcmfanatic1celebrate", "celebrate", "Celebrate", AnimationOptions = { EmoteLoop = true } },
    ["Cheering"] = { "Scenario", "WORLD_HUMAN_CHEERING", "Cheering" },
    ["Chill"] = { "switch@trevor@scares_tramp", "trev_scares_tramp_idle_tramp", "Chill", AnimationOptions = { EmoteLoop = true } },
    ["Ciggy"] = { "Scenario", "WORLD_HUMAN_AA_SMOKE", "Ciggy" },
    ["Clown 1"] = { "rcm_barry2", "clown_idle_0", "Clown 1", AnimationOptions = { EmoteLoop = true } },
    ["Clown 2"] = { "rcm_barry2", "clown_idle_1", "Clown 2", AnimationOptions = { EmoteLoop = true } },
    ["Clown 3"] = { "rcm_barry2", "clown_idle_2", "Clown 3", AnimationOptions = { EmoteLoop = true } },
    ["Clown 4"] = { "rcm_barry2", "clown_idle_3", "Clown 4", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Clown 5"] = { "rcm_barry2", "clown_idle_6", "Clown 5", AnimationOptions = { EmoteLoop = true } },
    ["Crawl"] = { "move_injured_ground", "front_loop", "Crawl", AnimationOptions = { EmoteLoop = true } },
    ["Crossarms 1"] = { "amb@world_human_hang_out_street@female_arms_crossed@idle_a", "idle_a", "Crossarms 1", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Crossarms 2"] = { "amb@world_human_hang_out_street@male_c@idle_a", "idle_b", "Crossarms 2", AnimationOptions = { EmoteMoving = true } },
    ["Crossarms 3"] = { "anim@heists@heist_corona@single_team", "single_team_loop_boss", "Crossarms 3", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Crossarms 4"] = { "random@street_race", "_car_b_lookout", "Crossarms 4", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Crossarms 5"] = { "anim@amb@nightclub@peds@", "rcmme_amanda1_stand_loop_cop", "Crossarms 5", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Crossarms 6"] = { "random@shop_gunstore", "_idle", "Crossarms 6", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Crossarms Side"] = { "rcmnigel1a_band_groupies", "base_m2", "Crossarms Side", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Crouch 1"] = { "move_aim_strafe_crouch_2h", "idle", "Crouch 1", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Crouch 2"] = { "missfbi2", "franklin_sniper_crouch", "Crouch 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Crouch 3"] = { "move_weapon@rifle@generic", "idle_crouch", "Crouch 3", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Cutthroat"] = { "anim@mp_player_intcelebrationmale@cut_throat", "cut_throat", "Cut Throat" },
    ["Cutthroat 2"] = { "anim@mp_player_intcelebrationfemale@cut_throat", "cut_throat", "Cut Throat 2" },
    ["Cynical Laugh"] = { "anim@arena@celeb@flat@solo@no_props@", "taunt_e_player_b", "Cynical Laugh" },
    ["Dive Sprint"] = { "swimming@scuba", "dive_sprint", "Dive Sprint", AnimationOptions = { EmoteLoop = true } },
    ["Drill"] = { "Scenario", "WORLD_HUMAN_CONST_DRILL", "Drill" },
    ["Facepalm 1"] = { "random@car_thief@agitated@idle_a", "agitated_idle_a", "Facepalm 1", AnimationOptions = { EmoteMoving = true, EmoteDuration = 8000 } },
    ["Facepalm 2"] = { "anim@mp_player_intcelebrationfemale@face_palm", "face_palm", "Facepalm 2", AnimationOptions = { EmoteMoving = true, EmoteDuration = 8000 } },
    ["Facepalm 3"] = { "missminuteman_1ig_2", "tasered_2", "Facepalm 3", AnimationOptions = { EmoteMoving = true, EmoteDuration = 8000 } },
    ["Facepalm 4"] = { "anim@mp_player_intupperface_palm", "idle_a", "Facepalm 4", AnimationOptions = { EmoteMoving = true, EmoteLoop = true } },
    ["Fall Over 1"] = { "random@drunk_driver_1", "drunk_fall_over", "Fall Over 1" },
    ["Fall Over 2"] = { "mp_suicide", "pistol", "Fall Over 2" },
    ["Fall Over 3"] = { "mp_suicide", "pill", "Fall Over 3" },
    ["Fall Over 4"] = { "friends@frf@ig_2", "knockout_plyr", "Fall Over 4" },
    ["Fall Over 5"] = { "anim@gangops@hostage@", "victim_fail", "Fall Over 5" },
    ["Film Shocking"] = { "Scenario", "WORLD_HUMAN_MOBILE_FILM_SHOCKING", "Film Shocking" },
    ["Finger"] = { "anim@mp_player_intselfiethe_bird", "idle_a", "Finger", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Finger 2"] = { "anim@mp_player_intupperfinger", "idle_a_fp", "Finger 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Fishing"] = { "Scenario", "WORLD_HUMAN_STAND_FISHING", "Fishing" },
    ["Flashlight"] = { "Scenario", "WORLD_HUMAN_SECURITY_SHINE_TORCH", "Flashlight" },
    ["Flip"] = { "anim@arena@celeb@flat@solo@no_props@", "flip_a_player_a", "Flip" },
    ["Flip 2"] = { "anim@arena@celeb@flat@solo@no_props@", "cap_a_player_a", "Flip 2" },
    ["Fold Arms"] = { "anim@amb@business@bgen@bgen_no_work@", "stand_phone_phoneputdown_idle_nowork", "Fold Arms", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Fold Arms 2"] = { "anim@amb@nightclub@peds@", "rcmme_amanda1_stand_loop_cop", "Fold Arms 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Gardener"] = { "Scenario", "WORLD_HUMAN_GARDENER_PLANT", "Gardener" },
    ["Guitar"] = { "amb@world_human_musician@guitar@male@idle_a", "idle_b", "Guitar", AnimationOptions = { Prop = "prop_acc_guitar_01", PropBone = 24818, PropPlacement = { -0.1, 0.31, 0.1, 0.0, 20.0, 150.0 }, EmoteMoving = true, EmoteLoop = true } },
    ["Guitar 2"] = { "switch@trevor@guitar_beatdown", "001370_02_trvs_8_guitar_beatdown_idle_busker", "Guitar 2", AnimationOptions = { Prop = "prop_acc_guitar_01", PropBone = 24818, PropPlacement = { -0.05, 0.31, 0.1, 0.0, 20.0, 150.0 }, EmoteMoving = true, EmoteLoop = true } },
    ["Guitar Electric"] = { "amb@world_human_musician@guitar@male@idle_a", "idle_b", "Guitar Electric", AnimationOptions = { Prop = "prop_el_guitar_01", PropBone = 24818, PropPlacement = { -0.1, 0.31, 0.1, 0.0, 20.0, 150.0 }, EmoteMoving = true, EmoteLoop = true } },
    ["Guitar Electric 2"] = { "amb@world_human_musician@guitar@male@idle_a", "idle_b", "Guitar Electric 2", AnimationOptions = { Prop = "prop_el_guitar_03", PropBone = 24818, PropPlacement = { -0.1, 0.31, 0.1, 0.0, 20.0, 150.0 }, EmoteMoving = true, EmoteLoop = true } },
    ["Hammering"] = { "Scenario", "WORLD_HUMAN_HAMMERING", "Hammering" },
    ["Headbutt"] = { "melee@unarmed@streamed_variations", "plyr_takedown_front_headbutt", "Headbutt" },
    ["Lean Against Wall"] = { "amb@lo_res_idles@", "world_human_lean_male_foot_up_lo_res_base", "Lean Against Wall", AnimationOptions = { EmoteLoop = true } },
    ["Leaning With Phone"] = { "amb@world_human_leaning@male@wall@back@mobile@base", "base", "Leaning With Phone", AnimationOptions = { Prop = "prop_phone_proto", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteMoving = false, EmoteLoop = true } },
    ["Jump Out Skydive"] = { "veh@plane@lazer@exit_skydive", "fds_jump_out_skydive", "Jump Out Skydive" },
    ["Karate"] = { "anim@mp_player_intcelebrationfemale@karate_chops", "karate_chops", "Karate" },
    ["Karate 2"] = { "anim@mp_player_intcelebrationmale@karate_chops", "karate_chops", "Karate 2" },
    ["Key Fob"] = { "anim@mp_player_intmenu@key_fob@", "fob_click", "Key Fob", AnimationOptions = { EmoteLoop = false, EmoteMoving = true, EmoteDuration = 1000 } },
    ["Lapdance"] = { "mp_safehouse", "lap_dance_girl", "Lapdance" },
    ["Lapdance Idle"] = { "mini@strip_club@private_dance@idle", "priv_dance_idle", "Lapdance Idle", AnimationOptions = { EmoteLoop = true } },
    ["Lapdance 1"] = { "mini@strip_club@private_dance@part1", "priv_dance_p1", "Lapdance 1", AnimationOptions = { EmoteLoop = true } },
    ["Lapdance 2"] = { "mini@strip_club@private_dance@part2", "priv_dance_p2", "Lapdance 2", AnimationOptions = { EmoteLoop = true } },
    ["Lapdance 3"] = { "mini@strip_club@private_dance@part3", "priv_dance_p3", "Lapdance 3", AnimationOptions = { EmoteLoop = true } },
    ["Lapdance 4"] = { "mini@strip_club@private_dance@exit", "priv_dance_exit", "Lapdance 4", AnimationOptions = { EmoteLoop = true } },
    ["Leafblower"] = { "MaleScenario", "WORLD_HUMAN_GARDENER_LEAF_BLOWER", "Leafblower" },
    ["Ledge Eating"] = { "Scenario", "WORLD_HUMAN_SEAT_LEDGE_EATING", "Ledge Eating" },
    ["Maid"] = { "Scenario", "WORLD_HUMAN_MAID_CLEAN", "Maid" },
    ["Meditiate"] = { "rcmcollect_paperleadinout@", "meditiate_idle", "Meditiate", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Metal"] = { "anim@mp_player_intincarrockstd@ps@", "idle_a", "Metal", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Mind Control 1"] = { "rcmbarry", "mind_control_b_loop", "Mind Control 1", AnimationOptions = { EmoteLoop = true } },
    ["Mind Control 2"] = { "rcmbarry", "bar_1_attack_idle_aln", "Mind Control 2", AnimationOptions = { EmoteLoop = true } },
    ["Musician"] = { "MaleScenario", "WORLD_HUMAN_MUSICIAN", "Musician" },
    ["OK"] = { "anim@mp_player_intselfiedock", "idle_a", "OK", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Paparazzi"] = { "Scenario", "WORLD_HUMAN_PAPARAZZI", "Paparazzi" },
    ["Partying"] = { "Scenario", "WORLD_HUMAN_PARTYING", "Partying" },
    ["Peace"] = { "mp_player_int_upperpeace_sign", "mp_player_int_peace_sign", "Peace", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Prone"] = { "missfbi3_sniping", "prone_michael", "Prone", AnimationOptions = { EmoteLoop = false, EmoteMoving = false } },
    ["Prostitue High"] = { "Scenario", "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS", "Prostitue High" },
    ["Prostitue Low"] = { "Scenario", "WORLD_HUMAN_PROSTITUTE_LOW_CLASS", "Prostitue Low" },
    ["Push Ups"] = { "amb@world_human_push_ups@male@base", "base", "Push Ups", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Salute 1"] = { "anim@mp_player_intincarsalutestd@ds@", "idle_a", "Salute 1", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Salute 2"] = { "anim@mp_player_intincarsalutestd@ps@", "idle_a", "Salute 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Salute 3"] = { "anim@mp_player_intuppersalute", "idle_a", "Salute 3", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Selfie 1"] = { "anim@mp_player_intuppertake_selfie", "idle_a", "Selfie 1", AnimationOptions = { Prop = "prop_phone_proto", PropBone = 60309, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = false } },
    ["Selfie 2"] = { "cellphone@self@franklin@", "peace", "Selfie 2", AnimationOptions = { Prop = "prop_phone_proto", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = false } },
    ["Shush"] = { "anim@mp_player_intcelebrationfemale@shush", "shush", "Shush" },
    ["Sit On Chair 1"] = { "Scenario", "PROP_HUMAN_SEAT_CHAIR", "Sit On Chair 1" },
    ["Sit On Chair 2"] = { "Scenario", "PROP_HUMAN_SEAT_CHAIR_UPRIGHT", "Sit On Chair 1" },
    ["Slap"] = { "melee@unarmed@streamed_variations", "plyr_takedown_front_slap", "Slap", AnimationOptions = { EmoteLoop = true, EmoteMoving = true, EmoteDuration = 2000 } },
    ["Slapped 1"] = { "melee@unarmed@streamed_variations", "victim_takedown_front_slap", "Slapped 1", "Slapped 1" },
    ["Slapped 2"] = { "melee@unarmed@streamed_variations", "victim_takedown_front_backslap", "Slapped 2", "Slapped 2" },
    ["Slide 1"] = { "anim@arena@celeb@flat@solo@no_props@", "slide_a_player_a", "Slide 1" },
    ["Slide 2"] = { "anim@arena@celeb@flat@solo@no_props@", "slide_b_player_a", "Slide 2" },
    ["Slide 3"] = { "anim@arena@celeb@flat@solo@no_props@", "slide_c_player_a", "Slide 3" },
    ["Sleep"] = { "timetable@tracy@sleep@", "idle_c", "Sleep", AnimationOptions = { EmoteLoop = true } },
    ["Slugger"] = { "anim@arena@celeb@flat@solo@no_props@", "slugger_a_player_a", "Slugger" },
    ["Smoke 1"] = { "Scenario", "WORLD_HUMAN_SMOKING", "Smoke 1" },
    ["Smoke 2"] = { "Scenario", "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS", "Smoke 2" },
    ["Smoke Weed"] = { "MaleScenario", "WORLD_HUMAN_DRUG_DEALER", "Smoke Weed" },
    ["Smoking Pot"] = { "Scenario", "WORLD_HUMAN_SMOKING_POT", "Smoking Pot" },
    ["Space Pistol 1"] = { "amb@world_human_superhero@male@space_pistol@idle_a", "idle_a", "Space Pistol 1" },
    ["Space Pistol 2"] = { "amb@world_human_superhero@male@space_pistol@idle_a", "idle_b", "Space Pistol 2" },
    ["Space Pistol 3"] = { "amb@world_human_superhero@male@space_pistol@idle_a", "idle_c", "Space Pistol 3" },
    ["Space Pistol 4"] = { "amb@world_human_superhero@male@space_pistol@idle_b", "idle_d", "Space Pistol 4" },
    ["Space Pistol 5"] = { "amb@world_human_superhero@male@space_pistol@idle_b", "idle_e", "Space Pistol 5" },
    ["Space Pistol 6"] = { "amb@world_human_superhero@male@space_pistol@idle_b", "idle_f", "Space Pistol 6" },
    ["Spider Man"] = { "missexile3", "ex03_train_roof_idle", "Spider Man", AnimationOptions = { EmoteLoop = true } },
    ["Sprint"] = { "swimming@scuba", "sprint", "Sprint", AnimationOptions = { EmoteLoop = true } },
    ["Sprint Turn R"] = { "swimming@scuba", "dive_sprint_turn_r2", "Sprint Turn R", AnimationOptions = { EmoteLoop = true } },
    ["Sprint Turn L"] = { "swimming@scuba", "dive_sprint_turn_l2", "Sprint Turn L", AnimationOptions = { EmoteLoop = true } },
    ["Statue 1"] = { "Scenario", "WORLD_HUMAN_HUMAN_STATUE", "Statue 1" },
    ["Statue 2"] = { "fra_0_int-1", "cs_lamardavis_dual-1", "Statue 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Statue 3"] = { "club_intro2-0", "csb_englishdave_dual-0", "Statue 3", AnimationOptions = { EmoteLoop = true } },
    ["Stickup"] = { "random@countryside_gang_fight", "biker_02_stickup_loop", "Stick Up", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Stink"] = { "anim@mp_player_intcelebrationfemale@stinker", "stinker", "Stink", AnimationOptions = { EmoteMoving = true, EmoteLoop = true } },
    ["Sunbathe Back"] = { "Scenario", "WORLD_HUMAN_SUNBATHE_BACK", "Sunbathe Back" },
    ["Surrender"] = { "random@arrests@busted", "idle_a", "Surrender", AnimationOptions = { EmoteLoop = true } },
    ["Think 1"] = { "misscarsteal4@aliens", "rehearsal_base_idle_director", "Think 1", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Think 2"] = { "missheist_jewelleadinout", "jh_int_outro_loop_a", "Think 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Think 3"] = { "timetable@tracy@ig_8@base", "base", "Think 3", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Think 4"] = { "anim@amb@casino@hangout@ped_male@stand@02b@idles", "idle_a", "Think 4", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Think 5"] = { "mp_cp_welcome_tutthink", "b_think", "Think 5", AnimationOptions = { EmoteMoving = true, EmoteDuration = 2000 } },
    ["Thumbsup 1"] = { "anim@mp_player_intupperthumbs_up", "idle_a", "Thumbs Up 1", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Thumbsup 2"] = { "anim@mp_player_intselfiethumbs_up", "idle_a", "Thumbs Up 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = true } },
    ["Thumbsup 3"] = { "anim@mp_player_intincarthumbs_uplow@ds@", "enter", "Thumbs Up 3", AnimationOptions = { EmoteMoving = true, EmoteDuration = 3000 } },
    ["Twerk"] = { "switch@trevor@mocks_lapdance", "001443_01_trvs_28_idle_stripper", "Twerk", AnimationOptions = { EmoteLoop = true } },
    ["Watch Stripper"] = { "amb@world_human_strip_watch_stand@male_c@idle_a", "idle_b", "Watch Stripper", AnimationOptions = { EmoteMoving = false, EmoteDuration = 6000 } },
    ["Weed"] = { "Scenario", "WORLD_HUMAN_DRUG_PROCESSORS_WEED", "Weed" },
    ["Weights"] = { "Scenario", "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS", "Weights" },
    ["Welding"] = { "Scenario", "WORLD_HUMAN_WELDING", "Welding" },
    ["Whistle"] = { "taxi_hail", "hail_taxi", "Whistle", AnimationOptions = { EmoteMoving = true, EmoteDuration = 1300 } },
    ["Whistle 2"] = { "rcmnigel1c", "hailing_whistle_waive_a", "Whistle 2", AnimationOptions = { EmoteMoving = true, EmoteDuration = 2000 } },
    ["Sitting Yoga"] = { "misscarsteal1leadin", "devon_idle_02", "Sitting Yoga", AnimationOptions = { EmoteMoving = false } },
    ["Yoga"] = { "Scenario", "WORLD_HUMAN_YOGA", "Yoga" },
}

Animations.emotes2 = {
    ["Backpack"] = { "move_p_m_zero_rucksack", "idle", "Backpack", AnimationOptions = { Prop = "p_michael_backpack_s", PropBone = 24818, PropPlacement = { 0.07, -0.11, -0.05, 0.0, 90.0, 175.0 }, EmoteMoving = true, EmoteLoop = true } },
    ["Beans"] = { "anim@scripted@island@special_peds@pavel@hs4_pavel_ig5_caviar_p1", "base_idle", "Beans", AnimationOptions = { Prop = "h4_prop_h4_caviar_tin_01a", PropBone = 60309, PropPlacement = { 0.0, 0.0300, 0.0100, 0.0, 0.0, 0.0 }, SecondProp = "h4_prop_h4_caviar_spoon_01a", SecondPropBone = 28422, SecondPropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Beer 1"] = { "amb@world_human_drinking@coffee@male@idle_a", "idle_c", "Beer 1", AnimationOptions = { Prop = "prop_amb_beer_bottle", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Beer 2"] = { "anim@amb@nightclub@peds@", "amb_world_human_partying_female_partying_beer_base", "Beer 2", AnimationOptions = { Prop = "prop_amb_beer_bottle", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true } },
    ["Beer 3"] = { "amb@world_human_drinking@beer@male@idle_a", "idle_c", "Beer 3", AnimationOptions = { Prop = 'prop_amb_beer_bottle', PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.06, 0.0, 15.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Beer 4"] = { "amb@world_human_drinking@beer@male@idle_a", "idle_c", "Beer 4", AnimationOptions = { Prop = 'prop_amb_beer_bottle', PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.06, 0.0, 15.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Beer 5"] = { "amb@world_human_drinking@beer@male@idle_a", "idle_a", "Beer 5", AnimationOptions = { Prop = 'p_cs_bottle_01', PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Beer 6"] = { "amb@world_human_drinking@beer@male@idle_a", "idle_b", "Beer 6", AnimationOptions = { Prop = 'p_cs_bottle_01', PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = false, EmoteMoving = true } },
    ["Beer 7"] = { "amb@world_human_drinking@beer@male@idle_a", "idle_c", "Beer 7", AnimationOptions = { Prop = 'p_cs_bottle_01', PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = false } },
    ["BeerF 1"] = { "amb@world_human_drinking@beer@female@idle_a", "idle_a", "Beer Female", AnimationOptions = { Prop = 'prop_amb_beer_bottle', PropBone = 28422, PropPlacement = { 0.0, -0.0, 0.05, 15.0, 15.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["BeerF 2"] = { "amb@world_human_drinking@beer@female@idle_a", "idle_a", "Beer Female 3", AnimationOptions = { Prop = 'prop_amb_beer_bottle', PropBone = 28422, PropPlacement = { 0.0, -0.0, 0.05, 15.0, 15.0, 0.0 }, EmoteLoop = true, EmoteMoving = false } },
    ["Beg"] = { "amb@world_human_bum_freeway@male@base", "base", "Beg", AnimationOptions = { Prop = "prop_beggers_sign_03", PropBone = 58868, PropPlacement = { 0.19, 0.18, 0.0, 5.0, 0.0, 40.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Bong 1"] = { "anim@safehouse@bong", "bong_stage3", "Bong 1", AnimationOptions = { Prop = "hei_heist_sh_bong_01", PropBone = 18905, PropPlacement = { 0.10, -0.25, 0.0, 95.0, 190.0, 180.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Bong 2"] = { "anim@safehouse@bong", "bong_stage3", "Bong 2", AnimationOptions = { Prop = "xm3_prop_xm3_bong_01a", PropBone = 18905, PropPlacement = { 0.10, -0.25, 0.0, 95.0, 190.0, 180.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Box"] = { "anim@heists@box_carry@", "idle", "Box", AnimationOptions = { Prop = "hei_prop_heist_box", PropBone = 60309, PropPlacement = { 0.025, 0.08, 0.255, -145.0, 290.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Burger"] = { "mp_player_inteat@burger", "mp_player_int_eat_burger", "Burger", AnimationOptions = { Prop = "prop_cs_burger_01", PropBone = 18905, PropPlacement = { 0.13, 0.05, 0.02, -50.0, 16.0, 60.0 }, EmoteMoving = true } },
    ["Camera 1"] = { "amb@world_human_paparazzi@male@base", "base", "Camera 1", AnimationOptions = { Prop = "prop_pap_camera_01", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true, PtfxAsset = "scr_bike_business", PtfxName = "scr_bike_cfid_camera_flash", PtfxPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0 }, PtfxWait = 200 } },
    ["Camera 2"] = { "missfinale_c2mcs_1", "fin_c2_mcs_1_camman", "Camera 2", AnimationOptions = { Prop = "prop_v_cam_01", PropBone = 28422, PropPlacement = { 0.0, 0.0300, 0.0100, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Carry Pizza 1"] = { "anim@heists@box_carry@", "idle", "Carry Pizza 1", AnimationOptions = { Prop = "prop_pizza_box_02", PropBone = 28422, PropPlacement = { 0.0100, -0.1000, -0.1590, 20.0000007, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Carry Pizza 2"] = { "anim@move_f@waitress", "idle", "Carry Pizza 2", AnimationOptions = { Prop = "prop_pizza_box_01", PropBone = 28422, PropPlacement = { 0.0, -0.076, 0.024, 0.0, 0.0, 30.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Champagne Spray 1"] = { "anim@mp_player_intupperspray_champagne", "idle_a", "Champagne Spray 1", AnimationOptions = { Prop = "ba_prop_battle_champ_open", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteMoving = true, EmoteLoop = true, PtfxAsset = "scr_ba_club", PtfxName = "scr_ba_club_champagne_spray", PtfxPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, PtfxWait = 500 } },
    ["Champagne Spray 2"] = { "anim@mp_player_intcelebrationfemale@spray_champagne", "spray_champagne", "Champagne Spray 2", AnimationOptions = { Prop = "prop_champ_01b", PropBone = 28422, PropPlacement = { 0.0, 0.0, -0.2, 0.0, 0.0, 0.0 }, EmoteMoving = true, EmoteLoop = false, PtfxAsset = "scr_ba_club", PtfxName = "scr_ba_club_champagne_spray", PtfxPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, PtfxWait = 500 } },
    ["Cig"] = { "amb@world_human_smoking@male@male_a@enter", "enter", "Cig", AnimationOptions = { Prop = "prop_amb_ciggy_01", PropBone = 47419, PropPlacement = { 0.015, -0.009, 0.003, 55.0, 0.0, 110.0 }, EmoteMoving = true, EmoteDuration = 2600 } },
    ["Cigar"] = { "amb@world_human_smoking@male@male_a@enter", "enter", "Cigar", AnimationOptions = { Prop = "prop_cigar_02", PropBone = 47419, PropPlacement = { 0.010, 0.0, 0.0, 50.0, 0.0, -80.0 }, EmoteMoving = true, EmoteDuration = 2600 } },
    ["Cigar 2"] = { "amb@world_human_smoking@male@male_a@enter", "enter", "Cigar 2", AnimationOptions = { Prop = "prop_cigar_01", PropBone = 47419, PropPlacement = { 0.010, 0.0, 0.0, 50.0, 0.0, -80.0 }, EmoteMoving = true, EmoteDuration = 2600 } },
    ["Coffee"] = { "amb@world_human_drinking@coffee@male@idle_a", "idle_c", "Coffee", AnimationOptions = { Prop = "p_amb_coffeecup_01", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Donut"] = { "mp_player_inteat@burger", "mp_player_int_eat_burger", "Donut", AnimationOptions = { Prop = "prop_amb_donut", PropBone = 18905, PropPlacement = { 0.13, 0.05, 0.02, -50.0, 16.0, 60.0 }, EmoteMoving = true } },
    ["Energy Drink"] = { "anim_heist@arcade_combined@", "ped_male@_stand_withdrink@_01b@_idles_idle_c", "Energy Drink", AnimationOptions = { Prop = "sf_prop_sf_can_01a", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, -0.017, 0.0, 0.0 }, EmoteMoving = true } },
    ["Food Tray 1"] = { "anim@heists@box_carry@", "idle", "Food Tray 1", AnimationOptions = { Prop = "prop_food_cb_tray_02", PropBone = 28422, PropPlacement = { 0.0100, -0.0400, -0.1390, 20.0000007, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Food Tray 2"] = { "anim@move_f@waitress", "idle", "Food Tray 2", AnimationOptions = { Prop = "prop_food_tray_02", PropBone = 28422, PropPlacement = { 0.0, -0.076, 0.024, 0.0, 0.0, 30.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Garbage Bin 1"] = { "anim@heists@box_carry@", "idle", "Garbage Bin 1", AnimationOptions = { Prop = "prop_bin_07d", PropBone = 28422, PropPlacement = { -0.0100, -0.2200, -0.8600, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Garbage Bin 2"] = { "anim@heists@box_carry@", "idle", "Garbage Bin 2", AnimationOptions = { Prop = "prop_bin_08open", PropBone = 28422, PropPlacement = { 0.00, -0.420, -1.290, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Guitar"] = { "amb@world_human_musician@guitar@male@idle_a", "idle_b", "Guitar", AnimationOptions = { Prop = "prop_acc_guitar_01", PropBone = 24818, PropPlacement = { -0.1, 0.31, 0.1, 0.0, 20.0, 150.0 }, EmoteMoving = true, EmoteLoop = true } },
    ["Guitar 2"] = { "switch@trevor@guitar_beatdown", "001370_02_trvs_8_guitar_beatdown_idle_busker", "Guitar 2", AnimationOptions = { Prop = "prop_acc_guitar_01", PropBone = 24818, PropPlacement = { -0.05, 0.31, 0.1, 0.0, 20.0, 150.0 }, EmoteMoving = true, EmoteLoop = true } },
    ["Guitar Electric 1"] = { "amb@world_human_musician@guitar@male@idle_a", "idle_b", "Guitar Electric 1", AnimationOptions = { Prop = "prop_el_guitar_01", PropBone = 24818, PropPlacement = { -0.1, 0.31, 0.1, 0.0, 20.0, 150.0 }, EmoteMoving = true, EmoteLoop = true } },
    ["Guitar Electric 2"] = { "amb@world_human_musician@guitar@male@idle_a", "idle_b", "Guitar Electric 2", AnimationOptions = { Prop = "prop_el_guitar_03", PropBone = 24818, PropPlacement = { -0.1, 0.31, 0.1, 0.0, 20.0, 150.0 }, EmoteMoving = true, EmoteLoop = true } },
    ["Joint"] = { "amb@world_human_smoking@male@male_a@enter", "enter", "Joint", AnimationOptions = { Prop = "p_cs_joint_02", PropBone = 47419, PropPlacement = { 0.015, -0.009, 0.003, 55.0, 0.0, 110.0 }, EmoteMoving = true, EmoteDuration = 2600 } },
    ["Lawn Chair 1"] = { "timetable@ron@ig_5_p3", "ig_5_p3_base", "Lawn Chair 1", AnimationOptions = { Prop = "prop_skid_chair_02", PropBone = 0, PropPlacement = { 0.025, -0.2, -0.1, 45.0, -5.0, 180.0 }, EmoteLoop = true, EmoteMoving = false } },
    ["Lawn Chair 2"] = { "timetable@ron@ig_3_couch", "base", "Lawn Chair 2", AnimationOptions = { Prop = "prop_skid_chair_02", PropBone = 0, PropPlacement = { -0.05, 0.0, -0.2, 5.0, 0.0, 180.0 }, EmoteLoop = true, EmoteMoving = false } },
    ["Lawn Chair 3"] = { "timetable@reunited@ig_10", "base_amanda", "Lawn Chair 3", AnimationOptions = { Prop = "prop_skid_chair_02", PropBone = 0, PropPlacement = { 0.025, -0.15, -0.1, 45.0, 5.0, 180.0 }, EmoteLoop = true, EmoteMoving = false } },
    ["Lawn Chair 4"] = { "timetable@reunited@ig_10", "base_amanda", "Lawn Chair 4", AnimationOptions = { Prop = "hei_prop_hei_skid_chair", PropBone = 0, PropPlacement = { 0.025, -0.15, -0.1, 45.0, 5.0, 180.0 }, EmoteLoop = true, EmoteMoving = false } },
    ["Lawn Chair 5"] = { "timetable@reunited@ig_10", "base_amanda", "Lawn Chair 5", AnimationOptions = { Prop = "ex_mp_h_stn_chairarm_24", PropBone = 0, PropPlacement = { 0, -0.7, -0.15, 45.0, 5.0, 180.0 }, EmoteLoop = true, EmoteMoving = false } },
    ["Lawn Chair 6"] = { "timetable@reunited@ig_10", "base_amanda", "Lawn Chair 6", AnimationOptions = { Prop = "v_club_officechair", PropBone = 0, PropPlacement = { 0, -0.45, -0.4, 45.0, 5.0, 180.0 }, EmoteLoop = true, EmoteMoving = false } },
    ["Megaphone"] = { "anim@random@shop_clothes@watches", "base", "Megaphone", AnimationOptions = { Prop = "prop_megaphone_01", PropBone = 18905, PropPlacement = { 0.10, 0.03, -0.01, 0.0, 120.0, 60.0 }, EmoteMoving = true, EmoteLoop = true } },
    ["Notepad"] = { "missheistdockssetup1clipboard@base", "base", "Notepad", AnimationOptions = { Prop = "prop_notepad_01", PropBone = 18905, PropPlacement = { 0.1, 0.02, 0.05, 10.0, 0.0, 0.0 }, SecondProp = "prop_pencil_01", SecondPropBone = 58866, SecondPropPlacement = { 0.11, -0.02, 0.001, -120.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Patrol 1"] = { "amb@world_human_security_shine_torch@male@base", "base", "Patrol 1", AnimationOptions = { Prop = 'prop_cs_police_torch_02', PropBone = 60309, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 80.0000 }, EmoteLoop = true, EmoteMoving = true } },
    ["Patrol 2"] = { "amb@world_human_security_shine_torch@male@idle_b", "idle_e", "Patrol 2", AnimationOptions = { Prop = 'prop_cs_police_torch_02', PropBone = 60309, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 80.0000 }, EmoteLoop = true, EmoteMoving = true } },
    ["Patrol 3"] = { "amb@world_human_security_shine_torch@male@idle_a", "idle_a", "Patrol 3", AnimationOptions = { Prop = 'prop_cs_police_torch_02', PropBone = 60309, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 80.0000 }, EmoteLoop = true, EmoteMoving = true } },
    ["Patrol 4"] = { "amb@incar@male@patrol@torch@base", "base", "Patrol 4", AnimationOptions = { Prop = 'prop_cs_police_torch_02', PropBone = 28422, PropPlacement = { 0.0, -0.00100, 0.0, 0.0, 0.0, 90.0 }, SecondProp = 'prop_cs_hand_radio', SecondPropBone = 60309, SecondPropPlacement = { 0.0560, 0.0470, 0.0110, -43.82733, 164.6747, -7.5569 }, EmoteLoop = true, EmoteMoving = true } },
    ["Phone Call"] = { "cellphone@", "cellphone_call_listen_base", "Phone Call", AnimationOptions = { Prop = "prop_npc_phone_02", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Smoke 1"] = { "amb@world_human_aa_smoke@male@idle_a", "idle_c", "Smoke 1", AnimationOptions = { Prop = "prop_cs_ciggy_01", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Smoke 2"] = { "amb@world_human_aa_smoke@male@idle_a", "idle_b", "Smoke 2", AnimationOptions = { Prop = "prop_cs_ciggy_01", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Smoke 3"] = { "amb@world_human_smoking@female@idle_a", "idle_b", "Smoke 3", AnimationOptions = { Prop = "prop_cs_ciggy_01", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Show Badge/ID"] = { "anim@scripted@freemode@postertag@graffiti_spray@male@", "shake_can_idle_male", "Show Badge/ID", AnimationOptions = { Prop = "prop_fib_badge", PropBone = 28422, PropPlacement = { 0.018, -0.02, 0.123, -22.0, 14.0, 2.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Teddy"] = { "impexp_int-0", "mp_m_waremech_01_dual-0", "Teddy", AnimationOptions = { Prop = "v_ilev_mr_rasberryclean", PropBone = 24817, PropPlacement = { -0.20, 0.46, -0.016, -180.0, -90.0, 0.0 }, EmoteMoving = true, EmoteLoop = true } },
    ["Umbrella 1"] = { "rcmnigel1d", "base_club_shoulder", "Umbrella 1", AnimationOptions = { Prop = "p_amb_brolly_01_s", PropBone = 28422, PropPlacement = { 0.0700, 0.0100, 0.1100, 2.3402393, -150.9605721, 57.3374916 }, EmoteLoop = true, EmoteMoving = true } },
    ["Umbrella 2"] = { "amb@world_human_drinking@coffee@male@base", "base", "Umbrella 2", AnimationOptions = { Prop = "p_amb_brolly_01", PropBone = 57005, PropPlacement = { 0.15, 0.005, 0.0, 87.0, -20.0, 180.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Walking Stick"] = { "move_characters@lester@waiting", "lester_waitidle_base", "Walking Stick", AnimationOptions = { Prop = "prop_cs_walking_stick", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Weed Bucket"] = { "anim@heists@box_carry@", "idle", "Weed Bucket", AnimationOptions = { Prop = "bkr_prop_weed_bucket_open_01a", PropBone = 28422, PropPlacement = { 0.0, -0.1000, -0.1800, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Weed Plant 1"] = { "anim@heists@box_carry@", "idle", "Weed Plant 1", AnimationOptions = { Prop = "bkr_prop_weed_lrg_01b", PropBone = 60309, PropPlacement = { 0.138, -0.05, 0.23, -50.0, 290.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
    ["Whiskey"] = { "amb@world_human_drinking@coffee@male@idle_a", "idle_c", "Whiskey", AnimationOptions = { Prop = "prop_drink_whisky", PropBone = 28422, PropPlacement = { 0.01, -0.01, -0.06, 0.0, 0.0, 0.0 }, EmoteLoop = true, EmoteMoving = true } },
}

Animations.dances = {
    ["Dance Club 1"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_a_m01", "Dance Club 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance Club 2"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_a_m02", "Dance Club 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance Club 3"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_a_m03", "Dance Club 3", AnimationOptions = { EmoteLoop = true } },
    ["Dance Club 4"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_a_m05", "Dance Club 4", AnimationOptions = { EmoteLoop = true } },
    ["Dance Drink 1"] = { "anim@amb@nightclub_island@dancers@beachdanceprop@", "mi_idle_c_m01", "Dance Drink 1", AnimationOptions = { Prop = "prop_beer_amopen", PropBone = 28422, PropPlacement = { 0.0, 0.00, 0.0, 0.0, 0.0, 20.00 }, EmoteLoop = true, EmoteMoving = false } },
    ["Dance Drink 2"] = { "anim@amb@nightclub_island@dancers@beachdanceprop@", "mi_loop_f1", "Dance Drink 2", AnimationOptions = { Prop = "p_wine_glass_s", PropBone = 28422, PropPlacement = { 0.0, 0.0, -0.0900, 0.0, 0.0, 0.00 }, EmoteLoop = true, EmoteMoving = false } },
    ["Dance Drink 3"] = { "anim@amb@nightclub_island@dancers@beachdanceprop@", "mi_loop_m04", "Dance Drink 3", AnimationOptions = { Prop = "ba_prop_battle_whiskey_opaque_s", PropBone = 28422, PropPlacement = { -0.0100, 0.00, 0.0, 0.0, 0.0, 10.00 }, EmoteLoop = true, EmoteMoving = false } },
    ["Dance Drink 4"] = { "anim@amb@nightclub_island@dancers@beachdanceprops@male@", "mi_idle_b_m04", "Dance Drink 4", AnimationOptions = { Prop = "ba_prop_battle_whiskey_opaque_s", PropBone = 28422, PropPlacement = { -0.0100, 0.00, 0.0, 0.0, 0.0, 10.00 }, EmoteLoop = true, EmoteMoving = false } },
    ["Dance Drink 5"] = { "anim@amb@nightclub_island@dancers@crowddance_single_props@", "hi_dance_prop_09_v1_female^3", "Dance Drink 5", AnimationOptions = { Prop = "p_wine_glass_s", PropBone = 28422, PropPlacement = { 0.0, 0.0, -0.0900, 0.0, 0.0, 0.00 }, EmoteLoop = true, EmoteMoving = false } },
    ["Dance Drink 6"] = { "anim@amb@nightclub_island@dancers@crowddance_single_props@", "hi_dance_prop_09_v1_male^3", "Dance Drink 6", AnimationOptions = { Prop = "prop_beer_stzopen", PropBone = 28422, PropPlacement = { 0.0090, 0.0010, -0.0310, 180.0, 180.0, -69.99 }, EmoteLoop = true, EmoteMoving = false } }, --prop_beer_logopen
    ["Dance Drink 7"] = { "anim@amb@nightclub_island@dancers@crowddance_single_props@", "hi_dance_prop_11_v1_female^3", "Dance Drink 7", AnimationOptions = { Prop = "p_wine_glass_s", PropBone = 28422, PropPlacement = { 0.0, 0.0, -0.0900, 0.0, 0.0, 0.00 }, EmoteLoop = true, EmoteMoving = false } },
    ["Dance Drink 8"] = { "anim@amb@nightclub_island@dancers@crowddance_single_props@", "hi_dance_prop_11_v1_female^1", "Dance Drink 8", AnimationOptions = { Prop = "p_wine_glass_s", PropBone = 28422, PropPlacement = { 0.0, 0.0, -0.0900, 0.0, 0.0, 0.00 }, EmoteLoop = true, EmoteMoving = false } },
    ["Dance Salsa 1"] = { "anim@mp_player_intuppersalsa_roll", "idle_a", "Dance Salsa 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance Sway High 1"] = { "anim@amb@nightclub@mini@dance@dance_solo@beach_boxing@", "high_center", "Dance Sway High 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance Sway High 2"] = { "anim@amb@nightclub@mini@dance@dance_solo@beach_boxing@", "high_center_up", "Dance Sway High 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance Sway High 3"] = { "anim@amb@nightclub@mini@dance@dance_solo@beach_boxing@", "high_center_down", "Dance Sway High 3", AnimationOptions = { EmoteLoop = true } },
    ["Dance Tao 1"] = { "misschinese2_crystalmazemcs1_cs", "dance_loop_tao", "Dance Tao 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance Tao 2"] = { "misschinese2_crystalmazemcs1_ig", "dance_loop_tao", "Dance Tao 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance Default"] = { "missfbi3_sniping", "dance_m_default", "Dance Default", AnimationOptions = { EmoteLoop = true } },
    ["Dance Monkey 1"] = { "anim@amb@nightclub@mini@dance@dance_solo@techno_monkey@", "high_center", "Dance Monkey 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance Monkey 2"] = { "anim@amb@nightclub@mini@dance@dance_solo@techno_monkey@", "high_center_down", "Dance Monkey 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance Monkey 3"] = { "anim@amb@nightclub@mini@dance@dance_solo@techno_monkey@", "med_center_down", "Dance Monkey 3", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 1"] = { "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", "high_center_down", "Dance M 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 2"] = { "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", "high_center", "Dance M 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 3"] = { "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", "high_center_up", "Dance M 3", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 4"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_15_v1_male^5", "Dance M 4", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 5"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "mi_dance_facedj_09_v1_male^4", "Dance M 5", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 6"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_male^2", "Dance M 6", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 7"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_17_v2_male^5", "Dance M 7", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 8"] = { "anim@amb@nightclub_island@dancers@crowddance_facedj@", "mi_dance_facedj_15_v2_male^4", "Dance M 8", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 9"] = { "anim@amb@nightclub_island@dancers@crowddance_facedj@", "hi_dance_facedj_hu_15_v2_male^4", "Dance M 9", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 10"] = { "anim@amb@nightclub_island@dancers@crowddance_facedj@", "mi_dance_facedj_17_v2_male^4", "Dance M 10 ", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 11"] = { "anim@amb@nightclub_island@dancers@crowddance_facedj@", "hi_dance_facedj_hu_17_male^5", "Dance M 11", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 12"] = { "anim@amb@nightclub@dancers@podium_dancers@", "hi_dance_facedj_17_v2_male^5", "Dance M 11", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 13"] = { "anim@amb@nightclub@dancers@crowddance_single_props@hi_intensity", "hi_dance_prop_13_v2_male^2", "Dance M 12", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 14"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_a_m01", "Dance M 14", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 15"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_a_m02", "Dance M 15", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 16"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_a_m03", "Dance M 16", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 17"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_b_m01", "Dance M 17", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 18"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_b_m02", "Dance M 18", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 19"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_b_m03", "Dance M 19", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 20"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_c_m01", "Dance M 20", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 21"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_c_m02", "Dance M 21", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 22"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_c_m03", "Dance M 22", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 23"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_d_m01", "Dance M 23", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 24"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_d_m02", "Dance M 24", AnimationOptions = { EmoteLoop = true } },
    ["Dance M 25"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_d_m03", "Dance M 25", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 1"] = { "anim@amb@nightclub@dancers@solomun_entourage@", "mi_dance_facedj_17_v1_female^1", "Dance F 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 2"] = { "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_center", "Dance F 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 3"] = { "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_center_up", "Dance F 3", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 4"] = { "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_center_up", "Dance F 4", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 5"] = { "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_center_down", "Dance F5", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 6"] = { "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_left_up", "Dance F6", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 8"] = { "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_09_v2_female^1", "Dance F8", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 9"] = { "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_09_v2_female^3", "Dance F9", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 10"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_female^4", "Dance F 10", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 11"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "li_dance_facedj_13_v1_female^3", "Dance F 11", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 12"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_female^6", "Dance F 12", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 13"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_15_v2_female^3", "Dance F 13", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 14"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_17_v2_female^4", "Dance F 14", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 15"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v1_female^6", "Dance F 15", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 16"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v1_female^3", "Dance F 16", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 17"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "mi_dance_facedj_17_v1_female^4", "Dance F 17", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 18"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_15_v2_female^6", "Dance F 18", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 19"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_female^6", "Dance F 19", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 20"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v2_female^5", "Dance F 20", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 21"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_17_v2_female^1", "Dance F 21", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 22"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_15_v2_female^2", "Dance F 22", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 23"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_13_v2_female^1", "Dance F 23", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 24"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_female^3", "Dance F 24", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 25"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_15_v2_female^5", "Dance F 25", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 26"] = { "anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_17_v2_female^6", "Dance F 26", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 27"] = { "anim@amb@nightclub_island@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_hu_15_v1_female^3", "Dance F 27", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 28"] = { "anim@amb@nightclub_island@dancers@crowddance_facedj_transitions@", "trans_dance_facedj_li_to_hi_09_v1_male^2", "Dance F 28", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 29"] = { "anim@amb@nightclub_island@dancers@club@", "hi_idle_a_f01", "Dance F 29", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 30"] = { "anim@amb@nightclub_island@dancers@club@", "hi_idle_a_f02", "Dance F 30", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 31"] = { "anim@amb@nightclub_island@dancers@club@", "hi_idle_a_f03", "Dance F 31", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 32"] = { "anim@amb@nightclub_island@dancers@club@", "hi_idle_b_f01", "Dance F 32", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 33"] = { "anim@amb@nightclub_island@dancers@club@", "hi_idle_b_f02", "Dance F 33", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 34"] = { "anim@amb@nightclub_island@dancers@club@", "hi_idle_b_f03", "Dance F 34", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 35"] = { "anim@amb@nightclub_island@dancers@club@", "hi_idle_d_f01", "Dance F 35", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 36"] = { "anim@amb@nightclub_island@dancers@club@", "hi_idle_f_f02", "Dance F 36", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 37"] = { "anim@amb@nightclub_island@dancers@club@", "mi_idle_c_f03", "Dance F 37", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 39"] = { "anim@amb@nightclub_island@dancers@club@", "hi_idle_d_f02", "Dance F 38", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 40"] = { "anim@amb@nightclub_island@dancers@club@", "hi_idle_d_f03", "Dance F 40", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 41"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_a_f01", "Dance F 41", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 42"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_a_f02", "Dance F 42", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 43"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_b_f01", "Dance F 43", AnimationOptions = { EmoteLoop = true } },
    ["Dance F 44"] = { "anim@amb@nightclub_island@dancers@beachdance@", "hi_idle_b_f02", "Dance F 44", AnimationOptions = { EmoteLoop = true } },
    ["Dance Karate 1"] = { "anim@amb@nightclub@mini@dance@dance_solo@techno_karate@", "high_center", "Dance Karate 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance Karate 2"] = { "anim@amb@nightclub@mini@dance@dance_solo@techno_karate@", "high_center_up", "Dance Karate 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance Karate 3"] = { "anim@amb@nightclub@mini@dance@dance_solo@techno_karate@", "high_center_down", "Dance Karate 3", AnimationOptions = { EmoteLoop = true } },
    ["Dance Lazlow 1"] = { "anim@amb@nightclub@lazlow@hi_railing@", "ambclub_09_mi_hi_bellydancer_laz", "Dance Lazlow 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance Silly"] = { "special_ped@mountain_dancer@monologue_3@monologue_3a", "mnt_dnc_buttwag", "Dance Silly", AnimationOptions = { EmoteLoop = true } },
    ["Dance Silly 2"] = { "move_clown@p_m_zero_idles@", "fidget_short_dance", "Dance Silly 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance Silly 3"] = { "move_clown@p_m_two_idles@", "fidget_short_dance", "Dance Silly 3", AnimationOptions = { EmoteLoop = true } },
    ["Dance Silly 4"] = { "anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_11_buttwiggle_b_laz", "Dance Silly 4", AnimationOptions = { EmoteLoop = true } },
    ["Dance Silly 5"] = { "anim@amb@casino@mini@dance@dance_solo@female@var_b@", "high_center", "Dance Silly 5", AnimationOptions = { EmoteLoop = true } },
    ["Dance Silly 6"] = { "anim@mp_player_intcelebrationfemale@the_woogie", "the_woogie", "Dance Silly 6", AnimationOptions = { EmoteLoop = true } },
    ["Dance Silly 7"] = { "rcmnigel1bnmt_1b", "dance_loop_tyler", "Dance Silly 7", AnimationOptions = { EmoteLoop = true } },
    ["Dance Slow 2"] = { "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "low_center", "Dance Slow 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance Slow 3"] = { "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "low_center_down", "Dance Slow 3", AnimationOptions = { EmoteLoop = true } },
    ["Dance Slow 4"] = { "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", "low_center", "Dance Slow 4", AnimationOptions = { EmoteLoop = true } },
    ["Dance Tight 1"] = { "anim@amb@nightclub@mini@dance@dance_solo@sand_trip@", "high_center", "Dance Tight 1", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Tight 2"] = { "anim@amb@nightclub@mini@dance@dance_solo@sand_trip@", "high_center_up", "Dance Tight 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Tight 3"] = { "anim@amb@nightclub@mini@dance@dance_solo@sand_trip@", "high_center_down", "Dance Tight 3", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Tracy 1"] = { "timetable@tracy@ig_5@base", "base", "Dance Tracy 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance Tracy 2"] = { "timetable@tracy@ig_5@idle_a", "idle_a", "Dance Tracy 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance Tracy 3"] = { "timetable@tracy@ig_5@idle_a", "idle_b", "Dance Tracy 3", AnimationOptions = { EmoteLoop = true } },
    ["Dance Tracy 4"] = { "timetable@tracy@ig_5@idle_a", "idle_c", "Dance Tracy 4", AnimationOptions = { EmoteLoop = true } },
    ["Dance Tracy 5"] = { "timetable@tracy@ig_5@idle_b", "idle_d", "Dance Tracy 5", AnimationOptions = { EmoteLoop = true } },
    ["Dance Tracy 6"] = { "timetable@tracy@ig_5@idle_b", "idle_e", "Dance Tracy 6", AnimationOptions = { EmoteLoop = true } },
    ["Dance Tracy 7"] = { "timetable@tracy@ig_8@idle_a", "idle_a", "Dance Tracy 7", AnimationOptions = { EmoteLoop = true } },
    ["Dance Tracy 8"] = { "timetable@tracy@ig_8@idle_a", "idle_b", "Dance Tracy 8", AnimationOptions = { EmoteLoop = true } },
    ["Dance Tracy 9"] = { "timetable@tracy@ig_8@idle_a", "idle_c", "Dance Tracy 9", AnimationOptions = { EmoteLoop = true } },
    ["Dance Glowsticks 1"] = { "anim@amb@nightclub@lazlow@hi_railing@", "ambclub_13_mi_hi_sexualgriding_laz", "Dance Glowsticks 1", AnimationOptions = { Prop = "ba_prop_battle_glowstick_01", PropBone = 28422, PropPlacement = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }, SecondProp = "ba_prop_battle_glowstick_01", SecondPropBone = 60309, SecondPropPlacement = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }, EmoteLoop = true } },
    ["Dance Glowsticks 2"] = { "anim@amb@nightclub@lazlow@hi_railing@", "ambclub_12_mi_hi_bootyshake_laz", "Dance Glowsticks 2", AnimationOptions = { Prop = "ba_prop_battle_glowstick_01", PropBone = 28422, PropPlacement = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }, SecondProp = "ba_prop_battle_glowstick_01", SecondPropBone = 60309, SecondPropPlacement = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }, EmoteLoop = true } },
    ["Dance Glowsticks 3"] = { "anim@amb@nightclub@lazlow@hi_railing@", "ambclub_09_mi_hi_bellydancer_laz", "Dance Glowsticks 3", AnimationOptions = { Prop = "ba_prop_battle_glowstick_01", PropBone = 28422, PropPlacement = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }, SecondProp = "ba_prop_battle_glowstick_01", SecondPropBone = 60309, SecondPropPlacement = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }, EmoteLoop = true } },
    ["Dance Heated 1"] = { "anim@amb@nightclub@mini@dance@dance_paired@dance_f@", "ped_a_dance_idle", "Dance Heated 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance Heated 2"] = { "anim@amb@nightclub@mini@dance@dance_paired@dance_f@", "ped_b_dance_idle", "Dance Heated 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance Horse 1"] = { "anim@amb@nightclub@lazlow@hi_dancefloor@", "dancecrowd_li_15_handup_laz", "Dance Horse 1", AnimationOptions = { Prop = "ba_prop_battle_hobby_horse", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true } },
    ["Dance Horse 2"] = { "anim@amb@nightclub@lazlow@hi_dancefloor@", "crowddance_hi_11_handup_laz", "Dance Horse 2", AnimationOptions = { Prop = "ba_prop_battle_hobby_horse", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true } },
    ["Dance Horse 3"] = { "anim@amb@nightclub@lazlow@hi_dancefloor@", "dancecrowd_li_11_hu_shimmy_laz", "Dance Horse 3", AnimationOptions = { Prop = "ba_prop_battle_hobby_horse", PropBone = 28422, PropPlacement = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, EmoteLoop = true } },
    ["Dance Shuffle 1"] = { "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", "high_center", "Dance Shuffle 1", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Shuffle 2"] = { "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", "high_center_up", "Dance Shuffle 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Shuffle 3"] = { "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", "high_center_down", "Dance Shuffle 3", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Shuffle 4"] = { "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", "high_right_up", "Dance Shuffle 4", AnimationOptions = { EmoteLoop = true } },
    ["Dance Shuffle 5"] = { "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", "high_right_down", "Dance Shuffle 5", AnimationOptions = { EmoteLoop = true } },
    ["Dance Shy 1"] = { "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", "low_center", "Dance Shy 1", AnimationOptions = { EmoteLoop = true } },
    ["Dance Shy 2"] = { "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", "low_center_down", "Dance Shy 2", AnimationOptions = { EmoteLoop = true } },
    ["Dance Upper 1"] = { "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", "high_center", "Dance Upper 1", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Upper 2"] = { "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", "high_center_up", "Dance Upper 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V1 M 1"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v1_male^1", "Dance Crowd V1 M 1", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V1 M 2"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v1_male^2", "Dance Crowd V1 M 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V1 M 3"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v1_male^3", "Dance Crowd V1 M 3", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V1 M 4"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v1_male^4", "Dance Crowd V1 M 4", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V1 M 5"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v1_male^5", "Dance Crowd V1 M 5", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V1 M 6"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v1_male^6", "Dance Crowd V1 M 6", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 F 1"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_female^1", "Dance Crowd V2 F 1", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 F 2"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_female^2", "Dance Crowd V2 F 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 F 3"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_female^3", "Dance Crowd V2 F 3", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 F 4"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_female^4", "Dance Crowd V2 F 4", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 F 5"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_female^5", "Dance Crowd V2 F 5", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 F 6"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_female^6", "Dance Crowd V2 F 6", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 M 1"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_male^1", "Dance Crowdd V2 M 1", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 M 2"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_male^2", "Dance Crowd V2 M 2", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 M 3"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_male^3", "Dance Crowd V2 M 3", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 M 4"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_male^4", "Dance Crowd V2 M 4", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 M 5"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_male^5", "Dance Crowd V2 M 5", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 M 6"] = { "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_17_v2_male^6", "Dance Crowd V2 M 6", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
    ["Dance Crowd V2 M 7"] = { "anim@amb@nightclub_island@dancers@crowddance_groups@groupd@", "mi_dance_crowd_13_v2_male^1", "Dance Crowd V2 M 7", AnimationOptions = { EmoteLoop = true, EmoteMoving = false } },
}

Animations.dj = {
    ["DJ Blamadon 1"] = { "anim@amb@nightclub@djs@black_madonna@", "pose_a_idle_a_blamadon", "DJ Blamadon 1", AnimationOptions = { EmoteLoop = true } },
    ["DJ Blamadon 2"] = { "anim@amb@nightclub@djs@black_madonna@", "pose_a_idle_b_blamadon", "DJ Blamadon 2", AnimationOptions = { EmoteLoop = true } },
    ["DJ Blamadon 3"] = { "anim@amb@nightclub@djs@black_madonna@", "pose_a_idle_c_blamadon", "DJ Blamadon 3", AnimationOptions = { EmoteLoop = true } },
    ["DJ Blamadon 4"] = { "anim@amb@nightclub@djs@black_madonna@", "dance_b_idle_a_blamadon", "DJ Blamadon 4", AnimationOptions = { EmoteLoop = true } },
    ["DJ Blamadon 5"] = { "anim@amb@nightclub@djs@black_madonna@", "dance_b_idle_d_blamadon", "DJ Blamadon 5", AnimationOptions = { EmoteLoop = true } },
    ["DJ Blamadon 6"] = { "anim@amb@nightclub@djs@black_madonna@", "pose_b_idle_i_blamadon", "DJ Blamadon 6", AnimationOptions = { EmoteLoop = true } },
    ["DJ Blamadon 7"] = { "anim@amb@nightclub@djs@black_madonna@", "pose_c_idle_a_blamadon", "DJ Blamadon 7", AnimationOptions = { EmoteLoop = true } },
    ["DJ Blamadon 8"] = { "anim@amb@nightclub@djs@black_madonna@", "pose_c_idle_b_blamadon", "DJ Blamadon 8", AnimationOptions = { EmoteLoop = true } },
    ["DJ Blamadon 9"] = { "anim@amb@nightclub@djs@black_madonna@", "pose_c_idle_c_blamadon", "DJ Blamadon 9", AnimationOptions = { EmoteLoop = true } },
    ["DJ Blamadon 10"] = { "anim@amb@nightclub@djs@black_madonna@", "pose_c_idle_d_blamadon", "DJ Blamadon 10", AnimationOptions = { EmoteLoop = true } },
    ["DJ Blamadon 11"] = { "anim@amb@nightclub@djs@black_madonna@", "temp_blkmdna_set_blackmadonna", "DJ Blamadon 11", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 1"] = { "anim@amb@nightclub@djs@dixon@", "dixn_idle_trns_hp_hd_nk_dix", "DJ Dixon 1", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 2"] = { "anim@amb@nightclub@djs@dixon@", "temp_dxn_set_dixon", "DJ Dixon 2", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 3"] = { "anim@amb@nightclub@djs@dixon@", "dixn_idle_cntr_b_dix", "DJ Dixon 3", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 4"] = { "anim@amb@nightclub@djs@dixon@", "dixn_idle_cntr_g_dix", "DJ Dixon 4", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 5"] = { "anim@amb@nightclub@djs@dixon@", "dixn_idle_cntr_gb_dix", "DJ Dixon 5", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 6"] = { "anim@amb@nightclub@djs@dixon@", "dixn_sync_cntr_j_dix", "DJ Dixon 6", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 7"] = { "anim@amb@nightclub@djs@dixon@", "dixn_dance_open_a_dix", "DJ Dixon 7", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 8"] = { "anim@amb@nightclub@djs@dixon@", "dixn_dance_cntr_open_dix", "DJ Dixon 8", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 9"] = { "anim@amb@nightclub@djs@dixon@", "dixn_dance_a_dixon", "DJ Dixon 9", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 10"] = { "anim@amb@nightclub@djs@dixon@", "dixn_idle_trns_hp_hd_nk_dix", "DJ Dixon 10", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 11"] = { "anim@amb@nightclub@djs@dixon@", "dixn_idle_cntr_a_dix", "DJ Dixon 11", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 12"] = { "anim@amb@nightclub@djs@dixon@", "dixn_idle_lft_a_dix", "DJ Dixon 12", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 13"] = { "anim@amb@nightclub@djs@dixon@", "dixn_sync_lft_a_dix", "DJ Dixon 13", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 14"] = { "anim@amb@nightclub@djs@dixon@", "dixn_sync_cntr_a_dix", "DJ Dixon 14", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 15"] = { "anim@amb@nightclub@djs@dixon@", "dixn_sync_cntr_b_dix", "DJ Dixon 15", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 16"] = { "anim@amb@nightclub@djs@dixon@", "dixn_sync_cntr_c_dix", "DJ Dixon 16", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 17"] = { "anim@amb@nightclub@djs@dixon@", "dixn_sync_cntr_e_dix", "DJ Dixon 17", AnimationOptions = { EmoteLoop = true } },
    ["DJ Dixon 18"] = { "anim@amb@nightclub@djs@dixon@", "dixn_sync_cntr_f_dix", "DJ Dixon 18", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 1"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_d_mix_05_b_dj_ptrax", "DJ Ptrax 1", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 2"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_h_mix_11_dj_ptrax", "DJ Ptrax 2", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 3"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_m_mix_13_dj_ptrax", "DJ Ptrax 3", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 4"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_n_mix_16_dj_ptrax", "DJ Ptrax 4", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 5"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_a_q_r_17_headphones_dj_ptrax", "DJ Ptrax 5", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 6"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_n_q_l_21_headphones_dj_ptrax", "DJ Ptrax 6", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 7"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_p_q_r_05_dj_ptrax", "DJ Ptrax 7", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 8"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_o_q_l_10_dj_ptrax", "DJ Ptrax 8", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 9"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_aa_mix_19_dj_ptrax", "DJ Ptrax 9", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 10"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_b_mix_20_dj_ptrax", "DJ Ptrax 10", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 11"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_d_q_l_05_dj_ptrax", "DJ Ptrax 11", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 12"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_i_q_l_12_dj_ptrax", "DJ Ptrax 12", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 13"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_i_mix_19_dj_ptrax", "DJ Ptrax 13", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 14"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_x_mix_20_dj_ptrax", "DJ Ptrax 14", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 15"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_ii_mix_24_headphones_dj_ptrax", "DJ Ptrax 15", AnimationOptions = { EmoteLoop = true } },
    ["DJ Ptrax 16"] = { "anim@scripted@nightclub@dj@dj_ptrax@", "ptrx_idle_j_q_r_base_10_dj_ptrax", "DJ Ptrax 16", AnimationOptions = { EmoteLoop = true } },
    ["DJ Solomun 1"] = { "anim@amb@nightclub@djs@solomun@", "temp_slmn_set_solomun", "DJ Solomun 1", AnimationOptions = { EmoteLoop = true } },
    ["DJ Solomun 2"] = { "anim@amb@nightclub@djs@solomun@", "sol_idle_ctr_wide_a_sol", "DJ Solomun 2", AnimationOptions = { EmoteLoop = true } },
    ["DJ Solomun 3"] = { "anim@amb@nightclub@djs@solomun@", "sol_idle_ctr_wide_b_sol", "DJ Solomun 3", AnimationOptions = { EmoteLoop = true } },
    ["DJ Solomun 4"] = { "anim@amb@nightclub@djs@solomun@", "sol_idle_ctr_mid_c_sol", "DJ Solomun 4", AnimationOptions = { EmoteLoop = true } },
    ["DJ Solomun 5"] = { "anim@amb@nightclub@djs@solomun@", "sol_idle_ctr_mid_g_sol", "DJ Solomun 5", AnimationOptions = { EmoteLoop = true } },
    ["DJ Solomun 6"] = { "anim@amb@nightclub@djs@solomun@", "sol_idle_ctr_mid_h_sol", "DJ Solomun 6", AnimationOptions = { EmoteLoop = true } },
    ["DJ Solomun 7"] = { "anim@amb@nightclub@djs@solomun@", "sol_sync_g_sol", "DJ Solomun 7", AnimationOptions = { EmoteLoop = true } },
    ["DJ Solomun 8"] = { "anim@amb@nightclub@djs@solomun@", "sol_dance_i_sol", "DJ Solomun 8", AnimationOptions = { EmoteLoop = true } },
    ["DJ Solomun 9"] = { "anim@amb@nightclub@djs@solomun@", "sol_dance_l_sol", "DJ Solomun 9", AnimationOptions = { EmoteLoop = true } },
    ["DJ Solomun 10"] = { "anim@amb@nightclub@djs@solomun@", "sol_idle_ctr_mid_a_sol", "DJ Solomun 10", AnimationOptions = { EmoteLoop = true } },
    ["DJ Solomun 11"] = { "anim@amb@nightclub@djs@solomun@", "sol_trans_ctrwide_to_mid_a_sol", "DJ Solomun 11", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU CC 1"] = { "anim@amb@nightclub@djs@tale_of_us@", "tou_sync_a_talcc", "DJ TOU CC 1", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU CC 2"] = { "anim@amb@nightclub@djs@tale_of_us@", "temp_tou_set_tale_of_us_cc", "DJ TOU CC 2", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU CC 3"] = { "anim@amb@nightclub@djs@tale_of_us@", "tou_dance_f_cc", "DJ TOU CC 3", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU CC 4"] = { "anim@amb@nightclub@djs@tale_of_us@", "tou_dance_h_cc", "DJ TOU CC 4", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU CC 5"] = { "anim@amb@nightclub@djs@tale_of_us@", "tou_sync_i_cc", "DJ TOU CC 5", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU MM 1"] = { "anim@amb@nightclub@djs@tale_of_us@", "tou_dance_a_mm", "DJ TOU MM 1", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU MM 2"] = { "anim@amb@nightclub@djs@tale_of_us@", "tou_sync_a_talmm", "DJ TOU MM 2", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU MM 3"] = { "anim@amb@nightclub@djs@tale_of_us@", "tou_dance_d_mm", "DJ TOU MM 3", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU MM 4"] = { "anim@amb@nightclub@djs@tale_of_us@", "tou_dance_f_mm", "DJ TOU MM 4", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU MM 5"] = { "anim@amb@nightclub@djs@tale_of_us@", "temp_tou_set_tale_of_us_mm", "DJ TOU MM 5", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU MM 6"] = { "anim@amb@nightclub@djs@tale_of_us@", "tou_sync_b_mm", "DJ TOU MM 6", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU MM 7"] = { "anim@amb@nightclub@djs@tale_of_us@", "tou_sync_d_mm", "DJ TOU MM 7", AnimationOptions = { EmoteLoop = true } },
    ["DJ TOU MM 8"] = { "anim@amb@nightclub@djs@tale_of_us@", "tou_sync_g_mm", "DJ TOU MM 8", AnimationOptions = { EmoteLoop = true } },
}

return Animations
